# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 11:24
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='workout/uploads/categories/')),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Wednesday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='workout/uploads/exercises/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.Category')),
            ],
        ),
        migrations.CreateModel(
            name='GymSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('capacity', models.IntegerField()),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.Day')),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(choices=[(datetime.time(6, 0), '06:00 AM'), (datetime.time(6, 30), '06:30 AM'), (datetime.time(17, 30), '05:30 PM'), (datetime.time(18, 0), '06:00 PM')], unique=True)),
            ],
            options={
                'ordering': ('start_time',),
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('subtitle', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='workout/uploads/stories/')),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='gymsession',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.Slot', unique_for_date=True),
        ),
        migrations.AddField(
            model_name='gymsession',
            name='users_attended',
            field=models.ManyToManyField(related_name='sessions_attended', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gymsession',
            name='users_registered',
            field=models.ManyToManyField(related_name='sessions_registered', to=settings.AUTH_USER_MODEL),
        ),
    ]
