# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 08:27
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('workout', '0001_initial'), ('workout', '0002_auto_20170911_1858'), ('workout', '0003_auto_20170912_1119'), ('workout', '0004_auto_20170912_1213'), ('workout', '0005_auto_20170912_1438'), ('workout', '0006_auto_20170912_1439'), ('workout', '0007_auto_20170912_1518'), ('workout', '0008_auto_20170912_1522'), ('workout', '0009_auto_20170912_1702'), ('workout', '0010_auto_20170914_1216'), ('workout', '0011_auto_20170914_1256'), ('workout', '0012_auto_20170914_1304'), ('workout', '0013_auto_20170914_1326'), ('workout', '0014_auto_20170914_1347')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='workout/uploads/categories/')),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Wednesday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='uploads/exercises/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.Category')),
            ],
        ),
        migrations.CreateModel(
            name='GymSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('capacity', models.IntegerField()),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.Day')),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(choices=[(datetime.time(6, 0), '06:00 AM'), (datetime.time(6, 30), '06:30 AM'), (datetime.time(17, 30), '05:30 PM'), (datetime.time(18, 0), '06:00 PM'), (datetime.time(9, 0), '09:00 AM')], unique=True)),
            ],
            options={
                'ordering': ('start_time',),
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('subtitle', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='uploads/stories/')),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'ordering': ('-created',),
                'verbose_name_plural': 'stories',
            },
        ),
        migrations.AddField(
            model_name='gymsession',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.Slot', unique_for_date='date'),
        ),
        migrations.AddField(
            model_name='gymsession',
            name='users_attended',
            field=models.ManyToManyField(blank=True, related_name='sessions_attended', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gymsession',
            name='users_registered',
            field=models.ManyToManyField(blank=True, related_name='sessions_registered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='uploads/workout/categories/'),
        ),
        migrations.AddField(
            model_name='day',
            name='slots',
            field=models.ManyToManyField(to='workout.Slot'),
        ),
        migrations.AlterField(
            model_name='gymsession',
            name='capacity',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='gymsession',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='gymsession',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='gymsession',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='gymsession',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='gymsession',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='workout/static/images/categories/'),
        ),
        migrations.AlterField(
            model_name='day',
            name='name',
            field=models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='workout/static/workout/images/categories/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='uploads/categories/'),
        ),
    ]
