# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_gymcategory_gymexercise_workout'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gymcategory',
            options={'verbose_name_plural': 'gym categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/categories/'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/exercises/'),
        ),
        migrations.AlterField(
            model_name='gymcategory',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/gym_categories/'),
        ),
        migrations.AlterField(
            model_name='gymexercise',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/gym_exercises/'),
        ),
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/stories/'),
        ),
    ]
