# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 07:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0004_dailyweight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyweight',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique_for_date='date'),
        ),
        migrations.AlterField(
            model_name='dailyweight',
            name='weight',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='gymsession',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.Day', unique_for_date='date'),
        ),
    ]
